# Generated by Django 3.2.8 on 2021-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactspage_fagpage_formpage_librarypage_photogallerypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес предприятия')),
                ('telephones', models.CharField(max_length=100, verbose_name='Телефоны предприятия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email предприятия')),
            ],
        ),
    ]
