# Generated by Django 3.2.8 on 2021-10-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
    ]
