# Generated by Django 3.2.8 on 2021-10-29 12:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_footer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephones', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Телефоны предприятия')),
                ('address', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Адрес предприятия')),
            ],
            options={
                'verbose_name': 'Хедер',
                'verbose_name_plural': 'Хедеры',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футеры'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=wagtail.core.fields.RichTextField(max_length=100, verbose_name='Адрес предприятия'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telephones',
            field=wagtail.core.fields.RichTextField(max_length=100, verbose_name='Телефоны предприятия'),
        ),
    ]
