# Generated by Django 3.2.8 on 2021-10-30 07:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211029_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='article',
            field=wagtail.core.fields.StreamField([('article_image', wagtail.images.blocks.ImageChooserBlock(verbose_name='Изображение')), ('article_title', wagtail.core.blocks.CharBlock(verbose_name='Заголовок статьи')), ('article_content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], verbose_name='Содержание статьи'))], blank=True),
        ),
        migrations.AlterField(
            model_name='homeslidesimage',
            name='product_description',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Описание продукции'),
        ),
    ]
