# Generated by Django 3.2.8 on 2021-10-30 08:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0012_auto_20211030_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='article_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
